openapi: 3.0.0
info:
  license:
    name: MIT
  title: Swagger Docstore
  version: 1.0.1
servers:
- url: http://docstore.swagger.io/v1
paths:
  /docs:
    get:
      operationId: listDocs
      parameters:
      - description: How many items to return at one time (max 102)
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Docs'
          description: A paged array of docs
          headers:
            x-next:
              description: A link to the next page of responses
              explode: false
              schema:
                type: string
              style: simple
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: List all docs
      tags:
      - docs
      x-accepts:
      - application/json
  /docs/{docId}:
    get:
      operationId: showDocById
      parameters:
      - description: The id of the doc to retrieve
        explode: false
        in: path
        name: docId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doc'
          description: Expected response to a valid request
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Info for a specific doc
      tags:
      - docs
      x-accepts:
      - application/json
components:
  schemas:
    Doc:
      example:
        name: name
        id: 0
        tag: tag
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        tag:
          type: string
      required:
      - id
      - name
      type: object
    Docs:
      items:
        $ref: '#/components/schemas/Doc'
      type: array
    Error:
      example:
        code: 6
        message: message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object

