/*
 * Swagger Docstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.miyajima.trial01.api;

import com.miyajima.trial01.ApiException;
import com.miyajima.trial01.model.Doc;
import com.miyajima.trial01.model.Error;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocsApi
 */
@Disabled
public class DocsApiTest {

    private final DocsApi api = new DocsApi();

    /**
     * List all docs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listDocsTest() throws ApiException {
        UUID xRequestId = null;
        Integer limit = null;
        List<Doc> response = api.listDocs(xRequestId, limit);
        // TODO: test validations
    }

    /**
     * Info for a specific doc
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showDocByIdTest() throws ApiException {
        UUID xRequestId = null;
        String docId = null;
        Doc response = api.showDocById(xRequestId, docId);
        // TODO: test validations
    }

}
