openapi: 3.0.0
info:
  license:
    name: MIT
  title: Swagger Catstore
  version: 1.0.1
servers:
- url: http://catstore.swagger.io/v1
paths:
  /cats:
    get:
      operationId: listCats
      parameters:
      - description: How many items to return at one time (max 102)
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cats'
          description: A paged array of cats
          headers:
            x-next:
              description: A link to the next page of responses
              explode: false
              schema:
                type: string
              style: simple
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: List all cats
      tags:
      - cats
      x-accepts:
      - application/json
  /cats/{catId}:
    get:
      operationId: showCatById
      parameters:
      - description: The id of the cat to retrieve
        explode: false
        in: path
        name: catId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
          description: Expected response to a valid request
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Info for a specific cat
      tags:
      - cats
      x-accepts:
      - application/json
components:
  schemas:
    Cat:
      example:
        name: name
        id: 0
        tag: tag
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        tag:
          type: string
      required:
      - id
      - name
      type: object
    Cats:
      items:
        $ref: '#/components/schemas/Cat'
      type: array
    Error:
      example:
        code: 6
        message: message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object

