/*
 * Swagger Catstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.miyajima.trial02.api;

import com.miyajima.trial02.ApiException;
import com.miyajima.trial02.model.Cat;
import com.miyajima.trial02.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CatsApi
 */
@Disabled
public class CatsApiTest {

    private final CatsApi api = new CatsApi();

    /**
     * List all cats
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCatsTest() throws ApiException {
        Integer limit = null;
        List<Cat> response = api.listCats(limit);
        // TODO: test validations
    }

    /**
     * Info for a specific cat
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showCatByIdTest() throws ApiException {
        String catId = null;
        Cat response = api.showCatById(catId);
        // TODO: test validations
    }

}
